<?php
$local_vars = Array(
'update' => __("Update","wpas"),
'save' => __("Save","wpas"),
'application' => __("Application","wpas"),
'entity' => __("Entity","wpas"),
'relationship' => __("Relationship","wpas"),
'help' => __("Help","wpas"),
'form' => __("Form","wpas"),
'taxonomy' => __("Taxonomy","wpas"),
'attribute' => __("Attribute","wpas"),
'tab' => __("Tab","wpas"),
'view' => __("View","wpas"),
'widget' => __("Widget","wpas"),
'add_new_application_settings'  => __("Add New Application Settings","wpas"),
'update_application_settings'  => __("Update Application Settings","wpas"),
'add_new_role'  => __("Add New Role","wpas"),
'role' => __("Role","wpas"),
'add_new_tab'  => __("Add New Tab","wpas"),
'add_new_form'  => __("Add New Form","wpas"),
'add_new_widget'  => __("Add New Widget","wpas"),
'add_new_view'  => __("Add New View","wpas"),
'add_new_help'  => __("Add New Help","wpas"),
'add_new_relationship' => __("Add New Relationship","wpas"),
'add_new_taxonomy'  => __("Add New Taxonomy","wpas"),
'add_new_attribute'  => __("Add New Attribute","wpas"),
'edit_form_layout'  => __("Edit Form Layout","wpas"),
'edit_admin_layout'  => __("Edit Admin Layout","wpas"),
'add_new_entity'  => __("Add New Entity","wpas"),
'update_settings'  => __("Update Settings","wpas"),
'download'  => __("Download","wpas"),
'support_ticket'  => __("Please open a support ticket.","wpas"),
);
$form_vars = Array(
'req_missing_error' => __("Please add all required fields to the form layout.","wpas"),
'dupe_error' => __("Please check duplicate entries and try again.","wpas"),
'dropdown_error' => __("Please select an option for all dropdowns.","wpas"),
'size_error' => __("Please update element row sizes to the total of 12.","wpas"),
);
$layout_vars = Array(
'edit_tab_title' => __("Tab Title (edit me)","wpas"),
'edit_acc_title' => __("Accordion Title (edit me)","wpas"),
'edit_tab_gr_title' => __("Tab Group Title (edit me)","wpas"),
'edit_acc_gr_title' => __("Accordion Group Title (edit me)","wpas"),
'drag_drop' => __("DRAG AND DROP","wpas"),
);
$validate_vars = Array(
'nocap_err' => __("Please remove capital letters.","wpas"),
'nospace_err' => __("Please remove spaces.","wpas"),
'nodash_err' => __("Please remove dashes.","wpas"),
'check_num' => __("Must contain only integers or -1.","wpas"),
'check_int' => __("Must contain only integers.","wpas"),
'check_alpha_num' => __("Must contain only letters or numbers.","wpas"),
'check_alpha_num_dash' => __("Must contain only letters, numbers or dashes.","wpas"),
'check_alpha_dash_fa' => __("Must contain only letters and dashes and start with fa-.","wpas"),
'check_alpha_num_und' => __("Must contain only letters, numbers or underscores.","wpas"),
'check_alpha_num_und_dash' => __("Must contain only letters, numbers, underscores or dashes.","wpas"),
'check_alpha_num_comma' => __("Must contain only letters, numbers and commas.","wpas"),
'check_version' => __("Must contain only numbers and dots.","wpas"),
'check_semico' => __("You need to seperate each option value with a semicolon.","wpas"),
'no_reserved' => __("You cannot use reserved words.","wpas"),
'check_help' => __("Please select a different attach to or screen type.","wpas"),
'check_unique' => __("Please enter a unique name.","wpas"),
);

?>
